version: 0.2

env:
  variables:
    S3_TRAINING_URI: "s3://dana-minicapstone-ca/training-data/"
    MODEL_ARTIFACTS_S3: "s3://dana-minicapstone-ca/model-artifacts/"
    ENDPOINT_NAME: "sagemaker-scikit-learn-2025-04-16-03-57-33-651"
    IAM_ROLE_ARN: "arn:aws:iam::222634404112:role/SageMakerExecutionRole-ca"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt
  build:
    commands:
      # 1. Launch a SageMaker training job
      - |
        JOB_NAME=hvac-train-$(date +%s)
        echo "Starting training job $JOB_NAME"
        aws sagemaker create-training-job \
          --training-job-name $JOB_NAME \
          --algorithm-specification TrainingImage=683313688378.dkr.ecr.ca-central-1.amazonaws.com/sagemaker-scikit-learn:0.23-1-cpu-py3,TrainingInputMode=File \
          --role-arn $IAM_ROLE_ARN \
          --input-data-config '[{"ChannelName":"train","DataSource":{"S3DataSource":{"S3DataType":"S3Prefix","S3Uri":"'"$S3_TRAINING_URI"'","S3DataDistributionType":"FullyReplicated"}}}]' \
          --output-data-config '{"S3OutputPath":"'"$MODEL_ARTIFACTS_S3"'"}' \
          --resource-config '{"InstanceType":"ml.m5.xlarge","InstanceCount":1,"VolumeSizeInGB":10}'
      # 2. Wait for training to finish
      - |
        echo "Waiting for training to complete…"
        aws sagemaker wait training-job-completed-or-stopped --training-job-name $JOB_NAME
      # 3. Create new model from training artifacts
      - |
        MODEL_NAME=hvac-model-$(date +%s)
        echo "Creating model $MODEL_NAME"
        aws sagemaker create-model \
          --model-name $MODEL_NAME \
          --primary-container Image=683313688378.dkr.ecr.ca-central-1.amazonaws.com/sagemaker-scikit-learn:0.23-1-cpu-py3,ModelDataUrl=$MODEL_ARTIFACTS_S3$JOB_NAME/output/model.tar.gz \
          --execution-role-arn $IAM_ROLE_ARN
      # 4. Create a new endpoint config
      - |
        ENDPOINT_CONFIG=hvac-endpoint-config-$(date +%s)
        echo "Creating endpoint config $ENDPOINT_CONFIG"
        aws sagemaker create-endpoint-config \
          --endpoint-config-name $ENDPOINT_CONFIG \
          --production-variants VariantName=AllTraffic,ModelName=$MODEL_NAME,InitialInstanceCount=1,InstanceType=ml.m5.large,InitialVariantWeight=1
      # 5. Update your existing endpoint in‐place
      - |
        echo "Updating endpoint $ENDPOINT_NAME to use $ENDPOINT_CONFIG"
        aws sagemaker update-endpoint \
          --endpoint-name $ENDPOINT_NAME \
          --endpoint-config-name $ENDPOINT_CONFIG
artifacts:
  files:
    - "**/*"
